public class Dev_Usecase_17 {
    public Dev_Usecase_17(){
    String [] City_arr = new String[]{'Chennai','Pune','Delhi','Noida'};
        String[] industries = new String[]{'Energy', 'Apparal', 'Technology'};
            Integer[] salaries = new Integer[]{1000, 2000, 4000, 4000};
                
                for(Integer i = 0; i < 3; i++){
                    System.debug(City_arr[i]);
                }
    
}
}