public class Dev_Usecase_2 {
    public Integer add(Integer a1, Integer a2){
        Integer sum = a1+a2;
        return sum;
    }
    public String getName(String Name){
        String value = Name;
        return value;
    }
    public Integer calculate(Integer sal){
        Integer amount = sal;
        return amount;
    }
    public boolean getData(boolean value){
        boolean data = value;
        return data;
    }
}