public class Dev_Usecase_1 {
    public void calculate(String name, Integer age){
       System.debug('Name' +name);
       System.debug('Age' +age);
    } 
    public void setData(string city, String branch){
        System.debug('City' +city);
        System.debug('Branch' +branch);
    }
    public void add(Integer first_number, integer secong_number){
        System.debug('First Name' +first_number);
        System.debug('Second Number' +secong_number);   
    }
    public void details(String FirstName, String LastName, String Industry){
         System.debug('FirstName' +FirstName);
         System.debug('LastName' +LastName);
         System.debug('Industry' +Industry);
    }
}